" ============================================================================
" Netrw Directory Listing                                        (netrw v156)
"   /home/andreas
"   Sorted by      name
"   Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,\~\=\*$,*,\.o$,\.obj$,\.info$,\.swp$,\.bak$,\~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:special
" ==============================================================================
../
./
.cache/
.cinnamon/
.config/
.gconf/
.gnupg/
.icons/
.linuxmint/
.local/
.mozilla/
.themes/
.vim/
Desktop/
Documents/
Downloads/
Music/
Pictures/
Public/
Templates/
Videos/
git/
.ICEauthority
.Xauthority
.bash_logout
.bashrc
.dmrc
.face
.gtkrc-2.0
.gtkrc-xfce
.profile
.vboxclient-clipboard.pid
.vboxclient-display.pid
.vboxclient-draganddrop.pid
.vboxclient-seamless.pid
.viminfo
.xsession-errors
.xsession-errors.old
